#!/bin/bash
DIR=`dirname $0`

declare -i start_with=`date +%s`
time ${DIR}/enablesampling $*
declare -i end_with=`date +%s`

echo time with sampling on = $end_with - $start_with "(seconds)"
  
declare -i start_without=`date +%s`
$*
declare -i end_without=`date +%s`

echo time with sampling off = $end_without - $start_without "(seconds)"

